### ISSUE TITLE
Variable with type File is truncated

### ISSUE THREAD

**Issue by RulyAnggriawan** [arisnacg/nodejs-glabenv#2]
Hi, is this support variable with type `File` ?

I can see the full value on the exported file but `sync` only import first line of value.

i use below command to export and import
```
glabenv export  -r https://gitlab.com/repo-origin -o variables.env
glabenv sync -r https://gitlab.com/repo-destination --filepath variables.env
```

Img1. Variable Type File
![image](https://github.com/arisnacg/nodejs-glabenv/assets/48803747/c6839e8d-c2f3-40de-9480-db221acc4bb4)

**Comment by arisnacg** [comment]
Sorry for the late response. Currently, it not support sync environment variables with `File` type
